import type { Metadata } from "next";
import { Playfair_Display, Cactus_Classical_Serif, Noto_Serif } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['500', '800'],
  variable: '--font-playfair',
});

const cactus = Cactus_Classical_Serif({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-cactus',
});

const noto = Noto_Serif({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-noto',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${noto.variable} ${cactus.variable} ${noto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
